workspace(name = "test_workspace")

# Set up maven
local_repository(
    name = "maven_repository_rules",
    path = "../..",
)

load("@maven_repository_rules//maven:maven.bzl", "maven_repository_specification")
load(
    ":build_substitution_templates.bzl",
    "AUTO_VALUE_BUILD_SNIPPET_WITH_PLUGIN",
    "DAGGER_BUILD_SNIPPET_WITH_PLUGIN",
)
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

KOTLIN_VERSION = "1.3.31"
KOTLINC_ROOT = "https://github.com/JetBrains/kotlin/releases/download"
KOTLINC_SHA = "107325d56315af4f59ff28db6837d03c2660088e3efeb7d4e41f3e01bb848d6a"
KOTLIN_RULES_VERSION = "legacy-modded-0_26_1-02"
KOTLIN_RULES_SHA = "245d0bc1511048aaf82afd0fa8a83e8c3b5afdff0ae4fbcae25e03bb2c6f1a1a"

http_archive(
    name = "io_bazel_rules_kotlin",
    strip_prefix = "rules_kotlin-%s" % KOTLIN_RULES_VERSION,
    type = "zip",
    urls = ["https://github.com/cgruber/rules_kotlin/archive/%s.zip" % KOTLIN_RULES_VERSION],
    sha256 = KOTLIN_RULES_SHA,
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")

kotlin_repositories(compiler_release = {
  "urls": [
      "{root}/v{v}/kotlin-compiler-{v}.zip".format(root = KOTLINC_ROOT, v = KOTLIN_VERSION),
  ],
  "sha256": KOTLINC_SHA,
})

kt_register_toolchains()

DAGGER_VERSION = "2.21"

maven_repository_specification(
    name = "maven",

    # If true, then any pom files for which a pom_sha256 attribute is not supplied will be
    # insecurely cached (after first download) using hashes stored in this folder.
    cache_poms_insecurely = True, # default False

    # If supplied, this will be the alternate location for insecure sha hashes.
    #
    # This can be an absolute or a path relative to ${HOME}
    insecure_cache = ".cache/bazel_maven_repository", # This is the default

    # Enable the creation of older-style mangling where foo-bar becomes foo_bar (for migration)
    legacy_artifact_id_munge = True,

    # The artifact spec list.
    artifacts = {
        # This is the proper way to specify an artifact.  It contains the artifact, plus a configuration dictionary.
        # The config dictionary contains a sha256 hash. This both ensures the file downloaded is the expected one, but
        # also caches the file in bazel's "content addressable" cache, which survives build clean.
        "com.google.guava:guava:25.0-jre": {
            "sha256": "3fd4341776428c7e0e5c18a7c10de129475b69ab9d30aeafbb5c277bb6074fa9",

            # This is optional, but more secure. Failing this, the pom's sha will be locally
            # stored in the insecure_pom_cache
            "pom_sha256": "68c1ac2817572d6a6eb5c36072c37379f912ec75e99f6bc25aaa7ed2eb2b5ff1",
        },

        # This is how you specify an artifact that has no hash.  You must either supply a sha256 hash of the jar file
        # or specify that the dep is insecure.
        "com.google.dagger:dagger-compiler:%s" % DAGGER_VERSION: {"insecure": True},
        "com.google.dagger:dagger-producers:%s" % DAGGER_VERSION: {"insecure": True},
        "com.google.dagger:dagger-spi:%s" % DAGGER_VERSION: {"insecure": True},
        "com.google.dagger:dagger:%s" % DAGGER_VERSION: {
            "insecure": True,
            # This is how you overwrite the generated build snippet with text of your own.
            "build_snippet": DAGGER_BUILD_SNIPPET_WITH_PLUGIN.format(version = DAGGER_VERSION),
        },
        "com.google.code.findbugs:jsr305:3.0.2": {"insecure": True},
        "com.google.errorprone:javac-shaded:9+181-r4173-1": {"insecure": True},
        "com.google.googlejavaformat:google-java-format:1.6": {"insecure": True},
        "com.google.truth:truth:1.0": {
            "insecure": True,
            "testonly": True,
            "exclude": ["org.checkerframework:checker-qual"], # for demonstration - don't alter truth in a real project.
        },

        # These deps are extra deps to make sure we have a large corpus for performance testing.
        "androidx.annotation:annotation:1.0.2": {"insecure": True},
        "androidx.appcompat:appcompat:1.0.0": { "insecure": True },
        "androidx.arch.core:core-common:2.0.0": { "insecure": True },
        "androidx.arch.core:core-runtime:2.0.0": { "insecure": True },
        "androidx.asynclayoutinflater:asynclayoutinflater:1.0.0": { "insecure": True },
        "androidx.collection:collection:1.0.0": { "insecure": True },
        "androidx.coordinatorlayout:coordinatorlayout:1.0.0": { "insecure": True },
        "androidx.core:core:1.0.0": {"insecure": True},
        "androidx.cursoradapter:cursoradapter:1.0.0": { "insecure": True },
        "androidx.customview:customview:1.0.0": { "insecure": True },
        "androidx.documentfile:documentfile:1.0.0": { "insecure": True },
        "androidx.drawerlayout:drawerlayout:1.0.0": { "insecure": True },
        "androidx.fragment:fragment:1.0.0:aar": { "insecure": True },
        "androidx.interpolator:interpolator:1.0.0": { "insecure": True },
        "androidx.legacy:legacy-support-core-ui:1.0.0": { "insecure": True },
        "androidx.legacy:legacy-support-core-utils:1.0.0": { "insecure": True },
        "androidx.lifecycle:lifecycle-common:2.0.0": { "insecure": True },
        "androidx.lifecycle:lifecycle-livedata-core:2.0.0": { "insecure": True },
        "androidx.lifecycle:lifecycle-livedata:2.0.0": { "insecure": True },
        "androidx.lifecycle:lifecycle-runtime:2.0.0": { "insecure": True },
        "androidx.lifecycle:lifecycle-viewmodel:2.0.0": { "insecure": True },
        "androidx.loader:loader:1.0.0": { "insecure": True },
        "androidx.localbroadcastmanager:localbroadcastmanager:1.0.0": { "insecure": True },
        "androidx.print:print:1.0.0": { "insecure": True },
        "androidx.slidingpanelayout:slidingpanelayout:1.0.0": { "insecure": True },
        "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0": { "insecure": True },
        "androidx.test:monitor:1.1.0:aar": { "insecure": True },
        "androidx.test:runner:1.1.0:aar": { "insecure": True },
        "androidx.vectordrawable:vectordrawable-animated:1.0.0": { "insecure": True },
        "androidx.vectordrawable:vectordrawable:1.0.0": { "insecure": True },
        "androidx.versionedparcelable:versionedparcelable:1.0.0": { "insecure": True },
        "androidx.viewpager:viewpager:1.0.0": { "insecure": True },
        "com.almworks.sqlite4java:sqlite4java:0.282": {"insecure": True},
        "com.android.support:support-annotations:25.1.1": {"insecure": True},
        "com.android.tools.build:builder-model:2.3.0": {"insecure": True},  # tests regression #38
        "com.android.tools.jack:jack-api:0.13.0": {"insecure": True},
        "com.android.tools.jill:jill-api:0.10.0": {"insecure": True},
        "com.android.tools.layoutlib:layoutlib-api:25.3.0": {"insecure": True},
        "com.android.tools:annotations:25.3.0": {"insecure": True},
        "com.android.tools:common:25.3.0": {"insecure": True},
        "com.f2prateek.rx.preferences2:rx-preferences:2.0.0": { "insecure": True },
        "com.f2prateek.rx.preferences:rx-preferences:1.0.2": { "insecure": True },
        "com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework:2.1": {"insecure": True},
        "com.google.auto.value:auto-value-annotations:1.6.3": {"insecure": True},
        "com.google.auto.value:auto-value:1.6.3": {"insecure": True, "build_snippet": AUTO_VALUE_BUILD_SNIPPET_WITH_PLUGIN.format(version = "1.6.3")},
        "com.google.code.gson:gson:2.8.5": {"insecure": True},
        "com.google.errorprone:error_prone_annotations:2.1.3": {"insecure": True},
        "com.google.j2objc:j2objc-annotations:1.1": {"insecure": True},
        "com.google.protobuf:protobuf-java:2.6.1": {"insecure": True},
        "com.googlecode.java-diff-utils:diffutils:1.3.0": {"insecure": True},
        "com.googlecode.libphonenumber:libphonenumber:8.7.1": { "insecure": True },
        "com.ibm.icu:icu4j:53.1": {"insecure": True},
        "com.intellij:annotations:12.0": {"insecure": True},
        "com.jakewharton.retrofit:retrofit1-okhttp3-client:1.0.2": { "insecure": True },
        "com.jakewharton.threetenabp:threetenabp:1.2.1:aar": { "insecure": True },
        "com.nhaarman:mockito-kotlin-kt1.1:1.6.0": { "insecure": True },
        "com.nhaarman:mockito-kotlin:1.6.0": { "insecure": True },
        "com.squareup.okhttp3:logging-interceptor:4.0.0-RC1": { "insecure": True },
        "com.squareup.okhttp3:mockwebserver:4.0.0-RC1": { "insecure": True },
        "com.squareup.okhttp3:okhttp:3.12.0": { "insecure": True },
        "com.squareup.okio:okio:1.15.0": { "insecure": True },
        "com.squareup.retrofit2:adapter-rxjava2:2.6.0": { "insecure": True },
        "com.squareup.retrofit2:converter-gson:2.6.0": { "insecure": True },
        "com.squareup.retrofit2:converter-wire:2.6.0": { "insecure": True },
        "com.squareup.retrofit2:retrofit-mock:2.6.0": { "insecure": True },
        "com.squareup.retrofit2:retrofit:2.6.0": { "insecure": True },
        "com.squareup.retrofit:retrofit:1.9.0": { "insecure": True },
        "com.squareup.wire:wire-gson-support:2.2.0": { "insecure": True },
        "com.squareup.wire:wire-runtime:2.2.0": { "insecure": True },
        "com.squareup.workflow:workflow-core-jvm:0.20.0": { "insecure": True },
        "com.squareup:javapoet:1.11.1": {"insecure": True},
        "com.squareup:javawriter:2.5.0": {"insecure": True},
        "com.squareup:pollexor:2.0.4": { "insecure": True },
        "com.squareup:tape:1.2.3": { "insecure": True },
        "commons-codec:commons-codec:1.4": {"insecure": True},
        "commons-logging:commons-logging:1.1.1": {"insecure": True},
        "io.reactivex:rxjava:1.1.0": {"insecure": True},
        "io.reactivex.rxjava2:rxjava:2.2.6": {"insecure": True},
        "javax.annotation:javax.annotation-api:1.2": {"insecure": True},  # tests regression #40
        "javax.annotation:jsr250-api:1.0": {"insecure": True},
        "javax.inject:javax.inject:1": {"insecure": True},
        "junit:junit:4.13-beta-1": {"insecure": True, "testonly": True},
        "net.bytebuddy:byte-buddy-agent:1.8.15": {"insecure": True},
        "net.bytebuddy:byte-buddy:1.8.15": {"insecure": True},
        "net.ltgt.gradle.incap:incap:0.2": {"insecure": True},
        "net.sf.kxml:kxml2:2.3.0": {"insecure": True},
        "org.antlr:antlr4-runtime:4.5.3": {"insecure": True},
        "org.apache.commons:commons-compress:1.8.1": {"insecure": True},
        "org.apache.httpcomponents:httpclient:4.1.1": {"insecure": True},
        "org.apache.httpcomponents:httpcore:4.1": {"insecure": True},
        "org.apache.httpcomponents:httpmime:4.1": {"insecure": True},
        "org.bouncycastle:bcpkix-jdk15on:1.48": {"insecure": True},
        "org.bouncycastle:bcprov-jdk15on:1.48": {"insecure": True},
        "org.checkerframework:checker-compat-qual:2.5.5": {"insecure": True},
        "org.checkerframework:checker-qual:2.5.3": {"insecure": True},
        "org.codehaus.mojo:animal-sniffer-annotations:1.14": {"insecure": True},
        "org.hamcrest:hamcrest-core:1.3": {"insecure": True, "testonly": True},
        "org.hamcrest:hamcrest-library:1.3": {"insecure": True},
        "org.javassist:javassist:3.21.0-GA": {"insecure": True}, # Only needed if #62 is fixed.
        "org.jetbrains.kotlin:kotlin-reflect:%s" % KOTLIN_VERSION: {"insecure": True},
        "org.jetbrains.kotlin:kotlin-stdlib-common:%s" % KOTLIN_VERSION: {"insecure": True},
        "org.jetbrains.kotlin:kotlin-stdlib:%s" % KOTLIN_VERSION: {"insecure": True},
        "org.jetbrains.kotlin:kotlin-test-common:%s" % KOTLIN_VERSION: {"insecure": True},
        "org.jetbrains.kotlin:kotlin-test:%s" % KOTLIN_VERSION: {"insecure": True},
        "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.0-RC2": {"insecure": True},
        "org.jetbrains:annotations:13.0": {"insecure": True},
        "org.mockito:mockito-core:2.18.3": {"insecure": True},
        "org.objenesis:objenesis:2.6": {"insecure": True},
        "org.reactivestreams:reactive-streams:1.0.2": {"insecure": True},
        "org.reflections:reflections:0.9.11": {"insecure": True }, # test leniency related to #62.
        "org.threeten:threetenbp:1.4.0": { "insecure": True },
    },
    repository_urls = [
        "https://repo1.maven.org/maven2",
        "https://maven.google.com",
    ],

    # Because these apply to all targets within a group, it's specified separately from the artifact list.
    dependency_target_substitutes = {
        # Because we rewrite dagger -> dagger_api (and make a wrapper target "dagger" that exports the dagger
        # annotation processor) we need to rewrite the internal dependencies inside the com/google/dagger package
        # to reflect this.
        # "groupId": { "full bazel target": "full alternate target" }
        "com.google.dagger": {"@maven//com/google/dagger:dagger": "@maven//com/google/dagger:dagger-api"},
    },
)

android_sdk_repository(
    name = "androidsdk",
    api_level = 28,
    build_tools_version = "28.0.3",
)